GENRE_PRESETS: dict[str, dict] = {
    "xuanhuan": {
        "id": "xuanhuan",
        "name": "玄幻",
        "skills": ["world_builder", "combat_scenes", "outline_architect", "draft_writer"],
        "writing_rules": "# 玄幻写作规范\n\n## 力量体系\n- 明确划分境界等级，每级有清晰的能力边界\n- 突破需有充分铺垫，不可突兀升级\n- 法宝/丹药等外力需有来源和代价\n\n## 战斗描写\n- 战斗需体现境界差异和技巧运用\n- 大招需蓄力，不可随意释放\n- 战败需有合理原因，不可纯粹运气\n\n## 世界观\n- 宗门/势力需有等级体系\n- 地图需随境界提升逐步展开\n- 资源争夺是核心矛盾之一\n",
        "extra_folders": ["世界观/力量", "世界观/地域", "世界观/种族"],
    },
    "xianxia": {
        "id": "xianxia",
        "name": "仙侠",
        "skills": ["world_builder", "combat_scenes", "emotion_rendering", "outline_architect"],
        "writing_rules": "# 仙侠写作规范\n\n## 修仙体系\n- 修仙境界需有传统根基（炼气、筑基、金丹等）\n- 天劫/心魔是重要转折点\n- 仙凡之别需贯穿始终\n\n## 情感描写\n- 仙侠重情，道心与情劫交织\n- 师徒情、道侣情需细腻刻画\n- 斩情证道需有充分心理铺垫\n\n## 世界观\n- 三界六道需有完整设定\n- 因果报应是核心法则\n- 长生代价需反复强调\n",
        "extra_folders": ["世界观/修炼体系", "世界观/仙界", "世界观/灵脉"],
    },
    "wuxia": {
        "id": "wuxia",
        "name": "武侠",
        "skills": ["combat_scenes", "character_designer", "scene_description", "outline_architect"],
        "writing_rules": "# 武侠写作规范\n\n## 武功体系\n- 内功外功需分明，招式需有特色\n- 武学境界靠悟性和苦练，非天赋碾压\n- 绝学需有传承和代价\n\n## 人物塑造\n- 侠义精神是核心，不可无底线\n- 江湖恩怨需有因果\n- 正邪并非绝对，灰色人物更出彩\n\n## 场景描写\n- 江湖场景需有古风韵味\n- 打斗场景需有招式细节\n- 环境描写需服务于氛围\n",
        "extra_folders": ["世界观/江湖", "世界观/武功", "世界观/门派"],
    },
    "urban": {
        "id": "urban",
        "name": "都市",
        "skills": ["character_designer", "dialogue_writing", "scene_description", "emotion_rendering"],
        "writing_rules": "# 都市写作规范\n\n## 现代设定\n- 背景需符合现实逻辑，不可脱离常识\n- 职业描写需有基本专业性\n- 社会关系需符合现代人际逻辑\n\n## 对话描写\n- 都市对话需自然口语化\n- 职场对话需体现层级关系\n- 情感对话需含蓄有张力\n\n## 情节推进\n- 矛盾需源于现实困境\n- 解决方式需合理不可开挂\n- 节奏需紧凑，避免拖沓\n",
        "extra_folders": ["世界观/都市设定", "世界观/势力"],
    },
    "scifi": {
        "id": "scifi",
        "name": "科幻",
        "skills": ["world_builder", "outline_architect", "deep_thinking", "constraint_layered_design"],
        "writing_rules": "# 科幻写作规范\n\n## 科技设定\n- 核心科技需有自洽逻辑\n- 技术发展需有因果链\n- 不可随意引入未铺垫的黑科技\n\n## 逻辑严密\n- 因果关系需经得起推敲\n- 时间线需前后一致\n- 物理法则除非明确设定否则需遵守\n\n## 世界观\n- 社会结构需反映科技影响\n- 文明冲突需有深层原因\n- 未来需有合理推演\n",
        "extra_folders": ["世界观/科技体系", "世界观/星际设定", "世界观/规则"],
    },
    "mystery": {
        "id": "mystery",
        "name": "悬疑",
        "skills": ["expectation_manager", "strand_weave", "outline_architect", "deep_thinking"],
        "writing_rules": "# 悬疑写作规范\n\n## 线索布局\n- 核心线索需提前埋设但可隐藏\n- 误导线索需有合理解释\n- 不可在结尾突兀引入新线索\n\n## 节奏控制\n- 悬念需层层递进\n- 揭露时机需精准把控\n- 每个转折需有逻辑支撑\n\n## 真相揭露\n- 真相需在意料之外情理之中\n- 所有伏笔需回收\n- 不可用巧合解决核心谜题\n",
        "extra_folders": ["世界观/线索体系", "世界观/谜题"],
    },
    "history": {
        "id": "history",
        "name": "历史",
        "skills": ["world_builder", "character_designer", "scene_description", "constraint_layered_design"],
        "writing_rules": "# 历史写作规范\n\n## 历史准确性\n- 重大历史事件不可篡改\n- 社会制度需符合时代特征\n- 语言风格需有时代感\n\n## 人物塑造\n- 历史人物需尊重基本史实\n- 虚构人物需融入时代背景\n- 人物动机需符合时代价值观\n\n## 细节描写\n- 服饰器物需符合历史\n- 礼仪规矩需考究\n- 地理环境需准确\n",
        "extra_folders": ["世界观/历史背景", "世界观/制度", "世界观/风俗"],
    },
    "gongdou": {
        "id": "gongdou",
        "name": "宫斗",
        "skills": ["character_designer", "expectation_manager", "emotion_rendering", "dialogue_writing"],
        "writing_rules": "# 宫斗写作规范\n\n## 权谋描写\n- 宫廷斗争需有层级和规则\n- 阴谋需有铺垫和逻辑\n- 不可让角色突然降智\n\n## 人物关系\n- 后宫等级制度需清晰\n- 联盟与背叛需有利益驱动\n- 皇帝态度是核心变量\n\n## 对话艺术\n- 话中有话是基本手法\n- 表面恭维暗藏锋芒\n- 沉默和暗示比直说更有力\n",
        "extra_folders": ["世界观/后宫制度", "世界观/势力分布"],
    },
    "game": {
        "id": "game",
        "name": "游戏",
        "skills": ["world_builder", "combat_scenes", "outline_architect", "constraint_layered_design"],
        "writing_rules": "# 游戏写作规范\n\n## 游戏机制\n- 核心玩法需清晰描述\n- 数值体系需自洽\n- 升级/装备系统需有逻辑\n\n## 竞技描写\n- 比赛需有策略深度\n- 操作描写需有画面感\n- 团队配合需有战术设计\n\n## 世界观\n- 游戏世界需有完整生态\n- NPC需有独立人格\n- 玩家与世界的互动需有规则\n",
        "extra_folders": ["世界观/游戏机制", "世界观/副本", "世界观/等级"],
    },
    "wuxian": {
        "id": "wuxian",
        "name": "无限流",
        "skills": ["combat_scenes", "world_builder", "outline_architect", "strand_weave"],
        "writing_rules": "# 无限流写作规范\n\n## 副本设计\n- 每个副本需有独立完整的世界观\n- 副本难度需递进\n- 副本规则需在进入时明确\n\n## 剧情推进\n- 主线需贯穿所有副本\n- 支线需服务于角色成长\n- 副本间需有过渡和喘息\n\n## 角色成长\n- 能力获取需有代价\n- 心理变化需随经历积累\n- 团队关系需动态发展\n",
        "extra_folders": ["世界观/场景库", "世界观/规则", "世界观/积分"],
    },
    "zhibo": {
        "id": "zhibo",
        "name": "直播",
        "skills": ["dialogue_writing", "character_designer", "emotion_rendering", "scene_description"],
        "writing_rules": "# 直播写作规范\n\n## 直播格式\n- 需模拟真实直播节奏\n- 弹幕互动需有氛围感\n- 直播事件需有即时性\n\n## 对话描写\n- 主播语言需有个人风格\n- 弹幕需多样化有真实感\n- 互动需推动剧情发展\n\n## 情节设计\n- 直播事件需有意外性\n- 观众反应需合理\n- 线下生活与直播需交织\n",
        "extra_folders": ["世界观/直播设定", "世界观/观众互动"],
    },
    "honghuang": {
        "id": "honghuang",
        "name": "洪荒",
        "skills": ["world_builder", "combat_scenes", "outline_architect", "constraint_layered_design"],
        "writing_rules": "# 洪荒写作规范\n\n## 神话体系\n- 需基于中国神话体系构建\n- 混沌初开到封神需有时间线\n- 圣人/准圣/大罗等需有等级\n\n## 战斗描写\n- 洪荒战斗需有天地异象\n- 法宝需有来历和品级\n- 阵法需有玄妙描述\n\n## 世界观\n- 天道规则需贯穿始终\n- 因果业力需有体现\n- 气运之争是核心矛盾\n",
        "extra_folders": ["世界观/洪荒体系", "世界观/神兽", "世界观/大劫"],
    },
    "yanqing": {
        "id": "yanqing",
        "name": "言情",
        "skills": ["emotion_rendering", "character_designer", "dialogue_writing", "scene_description"],
        "writing_rules": "# 言情写作规范\n\n## 情感描写\n- 感情发展需有节奏，不可一蹴而就\n- 心理描写需细腻真实\n- 甜蜜与虐心需交替出现\n\n## 人物塑造\n- 男女主需有独立人格\n- 配角需有存在价值\n- 反派需有合理动机\n\n## 情节设计\n- 误会需有逻辑不可硬造\n- 分合需有情感基础\n- 结局需呼应开篇承诺\n",
        "extra_folders": ["世界观/情感设定", "世界观/关系网"],
    },
    "xitong": {
        "id": "xitong",
        "name": "系统流",
        "skills": ["world_builder", "constraint_layered_design", "outline_architect", "combat_scenes"],
        "writing_rules": "# 系统流写作规范\n\n## 系统机制\n- 系统规则需在早期明确\n- 奖惩机制需自洽\n- 系统不可成为万能工具\n\n## 数值设计\n- 属性/等级需有清晰体系\n- 数值增长需有节奏\n- 不可出现数值崩坏\n\n## 剧情推进\n- 任务需推动剧情发展\n- 系统提示需有个性\n- 系统与主角关系需有变化\n",
        "extra_folders": ["世界观/系统设定", "世界观/任务体系", "世界观/奖励"],
    },
    "youxi_lit": {
        "id": "youxi_lit",
        "name": "游戏文学",
        "skills": ["world_builder", "combat_scenes", "character_designer", "dialogue_writing"],
        "writing_rules": "# 游戏文学写作规范\n\n## 游戏叙事\n- 需平衡游戏性与文学性\n- 游戏机制需融入叙事\n- 玩家选择需影响故事走向\n\n## 角色塑造\n- 游戏角色需有深度背景\n- NPC需有独立故事线\n- 主角成长需与游戏进程同步\n\n## 世界构建\n- 游戏世界需有完整生态\n- 任务系统需有叙事逻辑\n- 多结局需有情感差异\n",
        "extra_folders": ["世界观/游戏世界", "世界观/角色职业", "世界观/副本"],
    },
    "cosmic_horror": {
        "id": "cosmic_horror",
        "name": "宇宙恐怖",
        "skills": ["world_builder", "emotion_rendering", "scene_description", "deep_thinking"],
        "writing_rules": "# 宇宙恐怖写作规范\n\n## 恐怖氛围\n- 未知比已知更可怕，留白多于描写\n- 渐进式揭露，不可过早暴露全貌\n- 日常中的异常比直接恐怖更有效\n\n## 世界观\n- 宇宙尺度下人类的渺小需贯穿始终\n- 不可名状之物需保持神秘\n- 理性崩溃是核心体验\n\n## 情感描写\n- 恐惧需从不安逐步升级\n- 理智侵蚀需有过程\n- 绝望感需层层递进\n",
        "extra_folders": ["世界观/不可知", "世界观/异象", "世界观/禁忌"],
    },
    "history_travel": {
        "id": "history_travel",
        "name": "历史穿越",
        "skills": ["world_builder", "character_designer", "constraint_layered_design", "outline_architect"],
        "writing_rules": "# 历史穿越写作规范\n\n## 穿越逻辑\n- 穿越原因需有交代\n- 现代知识的应用需有限制\n- 蝴蝶效应需有体现\n\n## 历史融合\n- 重大历史节点需谨慎处理\n- 现代观念与古代价值观需碰撞\n- 改变历史需有代价\n\n## 时间悖论\n- 需建立时间旅行规则\n- 因果循环需自洽\n- 不可随意打破已建立的规则\n",
        "extra_folders": ["世界观/时空规则", "世界观/历史差异", "世界观/蝴蝶效应"],
    },
}
